### ISSUE TITLE
questions about the BOM and build guide request

### ISSUE THREAD

**Issue by inkarnatlies** [ergohaven/stacked-cases#1]
Hello! I'm planning to cut this case + tenting and was wondering if there was a build guide? 

Also wanted to ask the following:

1. Is this a low profile or a high profile case? Does the top layer end at the switch plate or a "wall" layer? 

2. If it does end with the switch plate layer on top, would it be possible to print extra "wall" layers so that I can make it a high profile case? I'm assuming that I will have to adjust accordingly the length of the spacers and screws bought.

3. I noticed in the BOM that you mentioned "Middle Plate - 5mm/6mm/2x3mm acrylic". Did you mean that it is either 1x 5mm, 1x 6mm or 2x 3mm acrylic plates? Is there any difference in using either 5mm vs 6mm/2x3mm?

4. When you mention standoff spacers, did you mean the "columns" with two female threaded ends?

Thanks in advance!

**Comment by kissetfall** [comment]
1. Probably "low profile".
2. If you make it then it's possible.
3. Yeah. The difference in the size.
4. Yep.

**Comment by inkarnatlies** [comment]
yo thanks for the responses. i already sent in the files to cut before your reply hahaha but thanks anyways! hoping that everything is in order
